FROM ruby:3.1.0-slim-bullseye

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y --no-install-recommends git gcc g++ libffi-dev make
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app
RUN bundle install --jobs=3 --retry=3

ENTRYPOINT ["/app/docker/scripts/docker-entrypoint.sh"]
CMD ["./bin/console"]
